# Generated by Django 4.0.3 on 2022-03-29 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=70, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='product',
            name='director',
            field=models.CharField(max_length=70, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='play',
            field=models.IntegerField(blank=True, help_text='В месяцах', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Срок годности'),
        ),
    ]
