# Generated by Django 4.0.3 on 2022-03-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='data',
        ),
    ]
